# Generated by Django 4.2.13 on 2024-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_group_id_message_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
