# Generated by Django 4.2.13 on 2024-08-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
