# Generated by Django 4.2.13 on 2024-08-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_like_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.post_data'),
        ),
    ]
