# Generated by Django 4.2.13 on 2024-08-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_profile_id'),
        ('app', '0006_alter_image_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
