# Generated by Django 4.2.13 on 2024-08-06 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_user_id'),
        ('app', '0009_alter_like_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(default='999999', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
