# Generated by Django 4.2.13 on 2024-08-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='8c603c76-f86', editable=False, max_length=15, unique=True),
        ),
    ]
