# Generated by Django 4.2.13 on 2024-08-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
